### PR TITLE
Update to Fabric

### PR DESCRIPTION
**Pull request by hansdesmedt**
https://github.com/junina-de/react-native-haptic-feedback/issues/87

### CODE REVIEW

**Comment by hansdesmedt** [comment]
hey can you add the label 'hacktoberfest' 🙏

**Comment by angelo-hub** [comment]
damn i was about to try my hand at porting it today, glad it's already done

**Comment by cospin** [comment]
Hey @mkuczera, can you check this? 🙏

**Comment by angelo-hub** [comment]
Update on this: can we get it compatible with the 0.71 fabric changes? @hansdesmedt

**Comment by mkuczera** [comment]
Hi there, sorry for the late response.
@angelo-hub @hansdesmedt I can also take a look for the 0.71 changes if you want

**Comment by angelo-hub** [comment]
@mkuczera that would be awesome! I know there's a few C++ module renames that happened

**Pull request merged**
