### PR TITLE
fix: make new arch work on iOS

### PR DESCRIPTION
**Pull request by WoLewicki**
PR making the library work on `iOS` with new arch enabled. For some reason, `exports` field makes the codegen on `iOS` omit this library. Also, `RNHapticFeedbackSpec.h` is a generated file and it should not be included as a separate one. cc @mkuczera could you elaborate why was it done like that?

### CODE REVIEW

**Review by huextrat — APPROVED** [review]
Tested with a patch ✅

**Comment by adriaanslechtenklarna** [comment]
Looking forward to this one. Thanks for fixing it!

**Comment by akindoju** [comment]
Nice! Really need this

**Comment by kesha-antonov** [comment]
Looks great

**Comment by mkuczera** [comment]
Awesome. Thank you for the contribution. @WoLewicki i think i missed the adjustment due to xcode build erros i had. But will test it out asap

**Pull request merged**
